name: Build & Release

on:
  push:
    tags:
      - "v*.*.*"   # wird ausgelöst, wenn du einen neuen Tag wie v1.2.3 pushst

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (falls nötig, sonst z. B. Python, Go, etc.)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build project
        run: |
          mkdir -p dist
          echo "Hello OpenHABian Release" > dist/hello.txt
          # hier stattdessen dein echter Build-Befehl

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
