name: Upload Fork Build Artifacts to Release

on:
  release:
    types: [published]      # automatisch beim Release
  workflow_dispatch:        # optional manuell startbar

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Download der Artefakte aus dem letzten erfolgreichen Build-Workflow
      - name: Download last build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts   # genau der Name, den dein Build-Workflow beim Upload verwendet
          path: ./dist            # wo die Artefakte lokal gespeichert werden

      # Optional: Anzeige der Dateien
      - name: List downloaded artifacts
        run: ls -lh ./dist

      # Upload der Artefakte ins Release
      - name: Upload artifacts to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
